// export methods
export { clamp } from "./methods/clamp"
export { constrain } from "./methods/constrain"
export { cropImage } from "./methods/cropImage"
export { getMousePos } from "./methods/getMousePos"
export { haveIntersection } from "./methods/haveIntersection"
export { inRange } from "./methods/inRange"
export { lerp } from "./methods/lerp"
export { loadFont } from "./methods/loadFont"
export { loadImage, getImage } from "./methods/loadImage"
export { map } from "./methods/map"
export { normalize } from "./methods/normalize"
export { random } from "./methods/random"
export { randomColor } from "./methods/randomColor"
export { Range, range } from "./methods/range"

// export on
export { onCollide } from "./on/onCollide"
export { onMouseDown } from "./on/onMouseDown"
export { onMouseMove } from "./on/onMouseMove"
export { onMouseUp } from "./on/onMouseUp"

// export shapes
export { Arc } from "./shapes/Arc"
export { Arrow } from "./shapes/Arrow"
export { Circle } from "./shapes/Circle"
export { Ellipse } from "./shapes/Ellipse"
export { Image } from "./shapes/Image"
export { Label } from "./shapes/Label"
export { Line } from "./shapes/Line"
export { Path } from "./shapes/Path"
export { Rect } from "./shapes/Rect"
export { RegularPolygon } from "./shapes/RegularPolygon"
export { Ring } from "./shapes/Ring"
export { Sprite } from "./shapes/Sprite"
export { Star } from "./shapes/Star"
export { Tag } from "./shapes/Tag"
export { getDummyContext, Text } from "./shapes/Text"
export { TextPath } from "./shapes/TextPath"
export { Wedge } from "./shapes/Wedge"

// export useApi
export { useClientActivated } from "./useApi/useClientActivated"
export { useEvent } from "./useApi/useEvent"
export { useMouseIsPressed } from "./useApi/useMouseIsPressed"
export { useMousePos } from "./useApi/useMousePos"
